#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:

  # Network Interface templates to use (these files must exist)
  OS::TripleO::Compute::Net::SoftwareConfig:
    /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig:
    /home/stack/templates/nic-configs/controller.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig:
    /home/stack/templates/nic-configs/ceph-storage.yaml
  OS::TripleO::NodeUserData:
    /home/stack/templates/firstboot.yaml

parameter_defaults:
  # This section is where deployment-specific configuration is done
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.10.11
  #ControlPlaneDefaultRoute: 172.17.11.1
  EC2MetadataIp: 192.168.10.11  # Generally the IP of the Undercloud
  # Customize the IP subnets to match the local environment
  InternalApiNetCidr: 192.168.15.0/24
  StorageNetCidr: 192.168.14.0/24
  StorageMgmtNetCidr: 192.168.12.0/24
  TenantNetCidr: 192.168.13.0/24
  ExternalNetCidr: 36.255.68.0/28
  # Customize the VLAN IDs to match the local environment
  InternalApiNetworkVlanID: 15
  StorageNetworkVlanID: 14
  StorageMgmtNetworkVlanID: 12
  TenantNetworkVlanID: 13
  ExternalNetworkVlanID: 36
  ManagementNetworkVlanID: 16
  # Customize the IP ranges on each network to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '192.168.15.200', 'end': '192.168.15.249'}]
  StorageAllocationPools: [{'start': '192.168.14.200', 'end': '192.168.14.249'}]
  StorageMgmtAllocationPools: [{'start': '192.168.12.200', 'end': '192.168.12.249'}]
  TenantAllocationPools: [{'start': '192.168.13.200', 'end': '192.168.13.249'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '36.255.68.11', 'end': '36.255.68.11'}]
  # Gateway router for the external network
  ExternalInterfaceDefaultRoute: 36.255.68.1
  # Uncomment if using the Management Network (see network-management.yaml)
  ManagementNetCidr: 192.168.16.0/24
  ManagementAllocationPools: [{'start': '192.168.16.200', 'end', '192.168.16.249'}]
  # Use either this parameter or ControlPlaneDefaultRoute in the NIC templates
  ManagementInterfaceDefaultRoute: 192.168.16.11
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["8.8.8.8","8.8.4.4"]
  # Set to empty string to enable multiple external networks or VLANs
  NeutronExternalNetworkBridge: "''"
  # The tunnel type for the tenant network (vxlan or gre). Set to '' to disable tunneling.
  NeutronTunnelTypes: 'vxlan'
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  BondInterfaceOvsOptions: "mode=802.3ad lacp_rate=fast updelay=1000 miimon=100"
  # Predictable VIPs
  ControlFixedIPs: [{'ip_address':'192.168.10.250'}]
  InternalApiVirtualFixedIPs: [{'ip_address':'192.168.15.250'}]
  PublicVirtualFixedIPs: [{'ip_address':'36.255.68.14'}]
  StorageVirtualFixedIPs: [{'ip_address':'192.168.14.250'}]
  StorageMgmtVirtualFixedIPs: [{'ip_address':'192.168.12.250'}]
  RedisVirtualFixedIPs: [{'ip_address':'192.168.15.251'}]
  NetConfigDataLookup:
    node1:
      nic1: "00:1b:21:27:20:62"
      nic2: "00:1b:21:27:20:63"
      nic3: "00:1b:21:28:03:49"
      nic4: "0c:c4:7a:de:a0:86"
      nic5: "0c:c4:7a:de:a0:87"
    node2:
      nic1: "12:00:1b:21:25:05"
      nic2: "12:00:1b:21:25:04"
      nic3: "00:1b:21:29:03:85"
      nic4: "ac:1f:6b:05:9f:c2"
      nic5: "ac:1f:6b:05:9f:c3"
    node3:
      nic1: "ec:f4:bb:c3:c0:0c"
      nic2: "ec:f4:bb:c3:c0:0d"
      nic3: "ec:f4:bb:c3:c0:0e"
      nic4: "a0:36:9f:27:b2:b4"
      nic5: "a0:36:9f:27:b2:b6"
